# Generated by Django 4.0.1 on 2022-01-11 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa: E501
                ('text', models.TextField(unique=True)),
                ('created', models.DateTimeField()),
                ('deadline', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa: E501
                ('solution', models.CharField(max_length=50)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa: E501
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # noqa: E501
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('homework_done', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.homeworkresult')),  # noqa: E501
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='homeworkresult',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.student'),  # noqa: E501
        ),
        migrations.AddField(
            model_name='homeworkresult',
            name='homework',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.homework', to_field='text'),  # noqa: E501
        ),
    ]
