# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    paths-ignore:
      - "polls/**"

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with flake8, isort and possibly run tests
    container: python:3.9

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          pip install -r requirements.txt
          ls -la
          flake8 .
          isort --check .
          py.test .
